---
version: "3.8"

x-hadoop-common:
  &hadoop-common
  image: hadoop-base:3.3.4
  # build:
  #   context: .
  #   dockerfile: base.Dockerfile
  labels:
    autoheal: 'true'
  networks:
    - main-network
  env_file: ./hadoop.env
  restart: always

services:

  hadoop-namenode:
    <<: *hadoop-common
    container_name: hadoop-namenode
    hostname: hadoop-namenode
    command: namenode
    environment:
      - CLUSTER_NAME=main
    ports:
      # HADOOP_NAMENODE_PORT
      - target: 9000
        published: 9005
        mode: host
      # HADOOP_NAMENODE_WEBUI_PORT
      - target: 9870
        published: 9870
        mode: host
    volumes:
      - type: volume
        source: hadoop-namenode-volume
        # HDFS_CONF_dfs_namenode_name_dir
        target: /hadoop/dfs/namenode
      - type: bind
        source: ./data
        target: /workspace
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  hadoop-datanode:
    <<: *hadoop-common
    container_name: hadoop-datanode
    hostname: hadoop-datanode
    command: datanode
    expose:
      # HADOOP_DATANODE_PORT
      - 9864
    environment:
      SERVICE_PRECONDITION: "hadoop-namenode:9870"
    volumes:
      - type: volume
        source: hadoop-datanode-volume
        # HDFS_CONF_dfs_datanode_data_dir
        target: /hadoop/dfs/datanode
    depends_on:
      - hadoop-namenode
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9864"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  hadoop-resourcemanager:
    <<: *hadoop-common
    container_name: hadoop-resourcemanager
    hostname: hadoop-resourcemanager
    command: resourcemanager
    expose:
      # HADOOP_RESOURCEMANAGER_PORT
      - 8088
    environment:
      SERVICE_PRECONDITION: "hadoop-namenode:9000 hadoop-namenode:9870 hadoop-datanode:9864"
    depends_on:
      - hadoop-namenode
      - hadoop-datanode
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "8088"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  hadoop-nodemanager:
    <<: *hadoop-common
    container_name: hadoop-nodemanager
    hostname: hadoop-nodemanager
    command: nodemanager
    expose:
      # HADOOP_NODEMANAGER_PORT
      - 8042
    environment:
      SERVICE_PRECONDITION: "hadoop-namenode:9000 hadoop-namenode:9870 hadoop-datanode:9864 hadoop-resourcemanager:8088"
    volumes:
      - type: volume
        source: hadoop-nodemanager-volume
        # YARN_CONF_yarn_nodemanager_remote___app___log___dir
        target: /hadoop/yarn/nodemanager
    depends_on:
      - hadoop-namenode
      - hadoop-datanode
      - hadoop-resourcemanager
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "8042"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  hadoop-historyserver:
    <<: *hadoop-common
    container_name: hadoop-historyserver
    hostname: hadoop-historyserver
    command: historyserver
    expose:
      # HADOOP_HISTORYSERVER_PORT
      - 8188
    environment:
      SERVICE_PRECONDITION: "hadoop-namenode:9000 hadoop-namenode:9870 hadoop-datanode:9864 hadoop-resourcemanager:8088"
    volumes:
      - type: volume
        source: hadoop-historyserver-volume
        # YARN_CONF_yarn_timeline___service_leveldb___timeline___store_path
        target: /hadoop/yarn/timeline
    depends_on:
      - hadoop-namenode
      - hadoop-datanode
      - hadoop-resourcemanager
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "8188"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


networks:
  main-network:
    name: main-network
    external: false
    driver: bridge
    attachable: false


volumes:
  hadoop-namenode-volume:
  hadoop-datanode-volume:
  hadoop-nodemanager-volume:
  hadoop-historyserver-volume:
